# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luncheon', '0003_auto_20171005_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='googleStarRating',
        ),
        migrations.RemoveField(
            model_name='eatery',
            name='priceLevel',
        ),
    ]
