# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luncheon', '0004_auto_20171008_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='hoursOfOperation',
        ),
    ]
