# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('luncheon', '0006_auto_20171009_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='favorited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
