# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luncheon', '0008_auto_20171012_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatery',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
